language: node_js

node_js:
  - 10.15.3

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run eslint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: gh-pages
